version: '3.7'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  user-api:
    build: .
    environment:
      DB_HOST: db
    ports:
      - 10000:10000